name: Actualisation Prévisions Orages (ATFCM)

on:
  schedule:
    # 01h30 (Run 21Z), 04h30 (Run 00Z), 07h30 (Run 03Z), 10h30 (Run 06Z),
    # 13h30 (Run 09Z), 16h30 (Run 12Z), 19h30 (Run 15Z)
    - cron: '30 1,4,7,10,13,16,19 * * *'
  workflow_dispatch: # Bouton d'exécution manuelle

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Étape 1 - Récupération du code
        uses: actions/checkout@v4

      - name: Étape 2 - Configuration Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Étape 3 - Installation des dépendances
        run: pip install requests

      - name: Étape 4 - Lancement du modèle
        run: python generer_meteo.py

      - name: Étape 5 - Sauvegarde en production
        run: |
          git config --global user.name "Actions Bot ATFCM"
          git config --global user.email "actions@github.com"
          git add public/previsions_orages.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Mise à jour: Nouveau run météo" && git push)